/** Harbor City geometry and authored street services. */
export const ROAD_XS = [180, 480, 780, 1080, 1380, 1620];
export const ROAD_YS = [180, 440, 700, 960, 1220];
const districts = [
  { id: 'saint-brigid', name: 'Saint Brigid', x: 0, y: 0, w: 650, h: 620, color: '#71817c' },
  { id: 'breakwater', name: 'Breakwater', x: 0, y: 620, w: 650, h: 780, color: '#967d64' },
  { id: 'glassward', name: 'Glassward', x: 650, y: 0, w: 650, h: 620, color: '#8395a1' },
  { id: 'the-narrows', name: 'The Narrows', x: 650, y: 620, w: 650, h: 780, color: '#7c716a' },
  { id: 'ironhaven', name: 'Ironhaven', x: 1300, y: 0, w: 500, h: 1400, color: '#787f81' },
];
const roads = [
  ...ROAD_XS.map((x, i) => ({ id: `avenue-${i}`, x1: x, y1: 68, x2: x, y2: 1338, width: 80 })),
  ...ROAD_YS.map((y, i) => ({ id: `street-${i}`, x1: 68, y1: y, x2: 1690, y2: y, width: 80 })),
];
const buildings = [];
for (let row = 0; row < ROAD_YS.length - 1; row += 1) {
  for (let col = 0; col < ROAD_XS.length - 1; col += 1) {
    const x = ROAD_XS[col] + 64;
    const y = ROAD_YS[row] + 64;
    const availableWidth = ROAD_XS[col + 1] - ROAD_XS[col] - 128;
    const h = ROAD_YS[row + 1] - ROAD_YS[row] - 128;
    const district = districts.find(
      (item) => x >= item.x && x < item.x + item.w && y >= item.y && y < item.y + item.h,
    );
    const gap = col === 4 ? 13 : 18;
    const w = (availableWidth - gap) / 2;
    for (let wing = 0; wing < 2; wing += 1) {
      buildings.push({
        id: `block-${row}-${col}-${wing}`,
        x: x + wing * (w + gap),
        y,
        w,
        h,
        height: (14 + ((row * 13 + col * 7 + wing * 5) % 6) * 7) * 1.8 + 28,
        color: district.color,
        type: col > 3 ? 'warehouse' : row > 2 ? 'tenement' : 'office',
        district: district.id,
      });
    }
  }
}
const locations = [
  {
    id: 'felix-office',
    name: 'Voss Dispatch',
    type: 'home',
    x: 458,
    y: 700,
    color: '#dfbd62',
    description: 'Felix keeps the lights on here. Rest and save.',
  },
  {
    id: 'saira-shop',
    name: 'Saira’s Garage',
    type: 'garage',
    x: 780,
    y: 718,
    color: '#55cfc2',
    cost: 120,
    description: 'Repair your current vehicle · $120',
  },
  {
    id: 'clinic',
    name: 'Southbank Clinic',
    type: 'clinic',
    x: 180,
    y: 960,
    color: '#83dfae',
    cost: 60,
    description: 'Restore health · $60',
  },
  {
    id: 'armour-shop',
    name: 'Night Market Supply',
    type: 'armour',
    x: 1080,
    y: 192,
    color: '#b99aeb',
    cost: 180,
    description: 'Armour and ammunition · $180',
  },
  {
    id: 'weapon-shop',
    name: 'Rook’s Sporting Goods',
    type: 'weapons',
    x: 1380,
    y: 440,
    color: '#de8266',
    cost: 620,
    description: 'Buy shotgun, then SMG; refill ammo · $120',
  },
  {
    id: 'diner',
    name: 'The Blue Hour Diner',
    type: 'food',
    x: 480,
    y: 440,
    color: '#eabb75',
    cost: 18,
    description: 'Hot meal and a little peace · $18',
  },
  {
    id: 'taxi-rank',
    name: 'Harbor Taxi Rank',
    type: 'taxi',
    x: 480,
    y: 718,
    color: '#e7bd56',
    description: 'Pick up a paying passenger in a taxi.',
  },
  {
    id: 'imani-radio',
    name: 'Signal House',
    type: 'radio',
    x: 780,
    y: 440,
    color: '#76badd',
    description: 'Independent radio. Imani knows what the city hides.',
  },
  {
    id: 'port-depot',
    name: 'Pier 8 Depot',
    type: 'depot',
    x: 1620,
    y: 960,
    color: '#87c8bd',
    description: 'The night freight never stops.',
  },
];

locations.push(
  {
    id: 'blue-hour-lanes',
    name: 'Blue Hour Lanes',
    type: 'activity',
    activity: 'bowling',
    x: 411,
    y: 654,
    color: '#e3bd75',
    description: 'Ten-pin bowling · $10 admission',
  },
  {
    id: 'lantern-darts',
    name: 'The Lantern',
    type: 'activity',
    activity: 'darts',
    x: 723,
    y: 918,
    color: '#b39274',
    description: 'A full match of 301 darts · Free',
  },
  {
    id: 'saltworks-pool',
    name: 'Saltworks Billiards',
    type: 'activity',
    activity: 'pool',
    x: 1557,
    y: 915,
    color: '#77a9a1',
    description: 'Eight-ball pool · $20 wager',
  },
  {
    id: 'night-owl-arcade',
    name: 'Night Owl Arcade',
    type: 'activity',
    activity: 'arcade',
    x: 913,
    y: 413,
    color: '#ad9bbc',
    description: 'STACKLIGHT arcade game · $2 admission',
  },
);

const pickups = [
  {
    id: 'dispatch-tool-club',
    type: 'weapon',
    weapon: 'club',
    x: 132,
    y: 955,
    name: 'Utility club',
    ammo: 0,
  },
  {
    id: 'garage-workblade',
    type: 'weapon',
    weapon: 'knife',
    x: 737,
    y: 718,
    name: 'Workblade',
    ammo: 0,
  },
  {
    id: 'dispatch-sidearm',
    type: 'weapon',
    weapon: 'pistol',
    x: 434,
    y: 905,
    name: 'Pier Nine sidearm',
    ammo: 24,
  },
  {
    id: 'supply-heavy-sidearm',
    type: 'weapon',
    weapon: 'combat-pistol',
    x: 1427,
    y: 470,
    name: 'Magnus sidearm',
    ammo: 14,
  },
  {
    id: 'quay-pump-shotgun',
    type: 'weapon',
    weapon: 'shotgun',
    x: 180,
    y: 390,
    name: 'Gatekeeper pump shotgun',
    ammo: 12,
  },
  {
    id: 'port-combat-shotgun',
    type: 'weapon',
    weapon: 'combat-shotgun',
    x: 1660,
    y: 1030,
    name: 'Breachline semi-automatic shotgun',
    ammo: 16,
  },
  {
    id: 'market-compact-smg',
    type: 'weapon',
    weapon: 'smg',
    x: 1032,
    y: 700,
    name: 'Wren compact SMG',
    ammo: 60,
  },
  {
    id: 'narrows-service-smg',
    type: 'weapon',
    weapon: 'full-smg',
    x: 1335,
    y: 1180,
    name: 'Rook SM9',
    ammo: 60,
  },
  {
    id: 'port-assault-rifle',
    type: 'weapon',
    weapon: 'assault-rifle',
    x: 1380,
    y: 1040,
    name: 'Foundry AR',
    ammo: 60,
  },
  {
    id: 'glassward-carbine',
    type: 'weapon',
    weapon: 'carbine',
    x: 780,
    y: 240,
    name: 'Calder C4',
    ammo: 60,
  },
  {
    id: 'narrows-ranged-case',
    type: 'weapon',
    weapon: 'sniper',
    x: 1080,
    y: 1258,
    name: 'Coastwatch precision rifle',
    ammo: 10,
  },
  {
    id: 'port-precision-case',
    type: 'weapon',
    weapon: 'combat-sniper',
    x: 1620,
    y: 145,
    name: 'Overlook precision rifle',
    ammo: 12,
  },
  {
    id: 'port-rocket-case',
    type: 'weapon',
    weapon: 'rpg',
    x: 1658,
    y: 720,
    name: 'Hullbreaker launcher',
    ammo: 3,
  },
  {
    id: 'dock-grenade-case',
    type: 'weapon',
    weapon: 'grenade',
    x: 1422,
    y: 935,
    name: 'Fragmentation canisters',
    ammo: 3,
  },
  {
    id: 'narrows-fire-bottles',
    type: 'weapon',
    weapon: 'molotov',
    x: 434,
    y: 1150,
    name: 'Improvised fire bottles',
    ammo: 3,
  },
  {
    id: 'diner-glass-bottle',
    type: 'object',
    weapon: 'street-object',
    material: 'glass',
    x: 448,
    y: 472,
    name: 'Empty diner bottle',
    ammo: 1,
    respawnSeconds: 180,
  },
  {
    id: 'garage-metal-tool',
    type: 'object',
    weapon: 'street-object',
    material: 'metal',
    x: 812,
    y: 740,
    name: 'Loose metal tool',
    ammo: 1,
  },
  {
    id: 'quay-stone',
    type: 'object',
    weapon: 'street-object',
    material: 'stone',
    x: 162,
    y: 530,
    name: 'Quay-side rubble',
    ammo: 1,
  },
];

const obstacles = [
  {
    id: 'harbor-low-rail',
    x: 130,
    y: 710,
    w: 36,
    h: 5,
    height: 12,
    type: 'barrier',
    color: '#697c70',
  },
  {
    id: 'market-service-ledge',
    x: 519,
    y: 386,
    w: 34,
    h: 8,
    height: 24,
    type: 'ledge',
    color: '#898675',
  },
  {
    id: 'port-loading-ledge',
    x: 1660,
    y: 1000,
    w: 32,
    h: 44,
    height: 24,
    type: 'ledge',
    color: '#667779',
  },
];

export const WORLD = Object.freeze({
  width: 1800,
  height: 1400,
  roads,
  buildings,
  districts,
  locations,
  pickups,
  obstacles,
  water: [{ x: 1716, y: 0, w: 84, h: 1400 }],
  spawn: { x: 480, y: 700 },
  bounds: { left: 54, top: 54, right: 1708, bottom: 1360 },
  title: 'Harbor City',
  description: 'Five connected districts, one very long night.',
});
